import type { Metadata} from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Header } from './components/Header'
import { Footer } from './components/Footer'
import { RightMenu } from './components/RightMenu'




const inter = Inter({ subsets: ['latin'] })

//Сео
export const metadata: Metadata = {
  title: 'Travian World',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
       <body>
        <div className='wrapper'>
          <Header /> 
          <main className='main_conteiner'>
            <div className='children_wrapper'>{children}</div>
            <RightMenu />
          </main>
          <Footer />
        </div>
      </body>
  
  );
}
